# Autogenerated by devscripts/update-version.py

__version__ = '2025.01.13.014909'

RELEASE_GIT_HEAD = '722967ca07836253271df56271ef015678936702'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'InfinityLoop1308/yt-dlp'

ORIGIN = 'InfinityLoop1308/yt-dlp'

_pkg_version = '2025.01.13.014909'
