# Autogenerated by devscripts/update-version.py

__version__ = '2025.01.12.020915'

RELEASE_GIT_HEAD = 'a50b821faf6bbba19acb590579a1707e3c66a44e'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'InfinityLoop1308/yt-dlp'

ORIGIN = 'InfinityLoop1308/yt-dlp'

_pkg_version = '2025.01.12.020915'
