# Autogenerated by devscripts/update-version.py

__version__ = '2025.01.07.000003'

RELEASE_GIT_HEAD = '48dc77d417cea5adb5aa4735a3adcf623dd14ca5'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'InfinityLoop1308/yt-dlp'

ORIGIN = 'InfinityLoop1308/yt-dlp'

_pkg_version = '2025.01.07.000003'
